spring.application.name=time-series-project

server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000
spring.cache.type=redis

cache.query-ttl-minutes=5


influxdb.url=http://localhost:8086
influxdb.token=Z4hPLsBiB001xyAU7bYcTHoMqmqjAtiz89kSXUQTDpqjfMBXmzuhWHYSqd-IoaWCGxjXvQbAdi0mEgAMf6DXFw==
influxdb.org=weather-org
influxdb.bucket=weather_monitoring

open-meteo.archive-url=https://archive-api.open-meteo.com/v1/archive
open_meteo.air-quality-url=https://air-quality-api.open-meteo.com/v1/air-quality

logging.level.com.nais.time_series_project=INFO